import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import {ProSidebarProvider, useProSidebar} from 'react-pro-sidebar';
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Header from "@/components/Header";
import NextProgress from "next-progress";
import ContentWrapper from "@/components/ContentWrapper";

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ContentWrapper>
                <Header/>
                <Component {...pageProps} />
            </ContentWrapper>
        </>
    )
}
